
testBinaryTree: testBinaryTree.o binaryTree.o
	g++ -o testBinaryTree testBinaryTree.o binaryTree.o 
#注意前面必须是tab，不能是空格
testBinaryTree.o: testBinaryTree.cpp binaryTree.h
	g++ -g -c testBinaryTree.cpp
binaryTree.o: binaryTree.cpp
	g++ -c binaryTree.cpp
clean:
	rm testBinaryTree.o binaryTree.o testBinaryTree